# Generated by Django 4.1.2 on 2023-04-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigcart', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/'),
        ),
    ]
