# Generated by Django 4.1.2 on 2023-05-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigcart', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productName',
            field=models.TextField(blank=True, null=True),
        ),
    ]
